# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: „Das Wesen der Mathematik liegt in ihrer Freiheit“
subtitle: Georg Cantor
email: hong420@purdue.edu
description: >
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

category_list: [ Algebra, Analysis, Geometry, Etc ]
